version: "3.7"

services:
  namenode02:
    image: hadoop-namenode
    container_name: namenode02
    hostname: namenode02
    command: ["/start.sh", "standby"]
    ports:
      - "9870:9870" # namenode web UI
      - "50500:50500" # rpc port
      - "50501:49501" # zkfc port
      - "2181:2181" # zookeeper
      - "8485:8485" # journal

    depends_on:
      dummy_container:
        condition: service_healthy
    networks:
      - bridge
    environment:
      - NAMENODE_ID=${NAMENODE02_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870/"]
      interval: 30s
      timeout: 20s
      retries: 7
      start_period: 30s

  resourcemanager02:
    image: resourcemanager
    container_name: resourcemanager02
    hostname: resourcemanager02
    ports:
      - "8088:8088"
      - "8032:8032"
      - "8050:8050"
      - "8033:8033"
      - "8030:8030"
      - "8031:8031"
    environment:
      - RM_ID=${RM02_ID}
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 15s

  datanode01:
    container_name: datanode01
    hostname: datanode01
    image: hadoop-datanode
    networks:
    - bridge
    restart: on-failure:3
    ports:
      - "50101:50101"
      - "50100:50100" 
      - "50102:50102"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50101/"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 20s
    
    environment:
      - DATANODE_ADDRESS=${DATANODE01_ADDRESS}
      - DATANODE_HTTP=${DATANODE01_HTTP}
      - DATANODE_IPC=${DATANODE01_IPC}

  nodemgr02:
    image: hadoop-nm
    container_name: nodemgr02
    hostname: nodemgr02
    ports:
      - "50150:50150" # ipc
      - "50151:50151" # http
    environment:
      - NODEMGR_IPC=${NODEMGR02_IPC}
      - NODEMGR_HTTP=${NODEMGR02_HTTP}
      - NODEMGR_HOSTNAME=${NODEMGR02_HOSTNAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 20s

  dummy_container:
    image: dummy
    container_name: dummy_container
    hostname: dummy_container
    healthcheck:
      test: "/healthcheckNN02.sh &"
      interval: 15s
      timeout: 10s
      retries: 3
    restart: on-failure:5

networks:
  bridge: