version: "3.7"

#x-datanode_base: &datanode_base
#  image: hadoop-datanode
#  networks:
#    - bridge
#  restart: on-failure:3

services:
  resourcemanager01:
    image: resourcemanager
    container_name: resourcemanager01
    hostname: resourcemanager01
    ports:
      - "8088:8088"
      - "8032:8032"
      - "8050:8050"
      - "8033:8033"
      - "8030:8030"
      - "8031:8031"
    networks:
      hadoop_default: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/"]
      interval: 30s
      timeout: 20s
      retries: 7
      start_period: 15s

  namenode01:
    image: hadoop-namenode
    container_name: namenode01
    hostname: namenode01
    command: ["/start.sh", "active"]
    ports:
      - "9870:9870" # namenode web UI
      - "49500:49500" # rpc port
      - "49501:49501" # zkfc port
      - "2181:2181" # zookeeper
      - "8485:8485" # journal

    depends_on:
      dummy_container:
        condition: service_healthy
    networks:
      hadoop_default: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870/"]
      interval: 30s
      timeout: 20s
      retries: 7
      start_period: 30s
    #network_mode: host

  dummy_container:
    image: dummy
    container_name: dummy_container
    hostname: dummy_container
    networks:
      hadoop_default: {}
    healthcheck:
      test: "/healthcheckNN01.sh &"
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure:5

  zeppelin:
    image: zeppelin
    container_name: zeppelin
    hostname: zeppelin
    ports:
      - "9097:8080"
      - "5335:5335"
      - "18080:18080"
      - "4040:4040"
    networks:
      hadoop_default: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 7
      start_period: 30s

  datanode02:
    image: hadoop-datanode
    container_name: datanode02
    hostname: datanode02
    ports:
      - "49801:49801"
      - "49800:49800" 
      - "49802:49802"
      - "49603:8040"
      - "49604:8042"
    environment:
      - DATANODE02_ADDRESS=${DATANODE02_ADDRESS}
      - DATANODE02_HTTP=${DATANODE02_HTTP}
      - DATANODE02_IPC=${DATANODE02_IPC}
    networks:
      hadoop_default: {}

  datanode03:
    image: hadoop-datanode
    container_name: datanode03
    hostname: datanode03
    ports:
      - "49610:9864"
      - "49611:9866" 
      - "49612:9867"
      - "49613:8040"
      - "49614:8042"
    networks:
      hadoop_default: {}

networks:
  hadoop_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
          gateway: 172.80.0.1
    