version: "3.7"

x-datanode_base: &datanode_base
  image: hadoop-datanode
  networks:
    - bridge
  restart: on-failure:3

services:
  journal01:
    image: hadoop-journalnode
    container_name: journal01
    hostname: journal01
    ports:
      - "8480:8480"
      - "8485:8485"
    networks:
      - bridge
    restart: on-failure:3
      
  zookeeper01:
    image: hadoop-zookeeper
    container_name: zookeeper01
    hostname: zookeeper01
    ports :
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - bridge
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=${AWS2HOSTNAME}:2888:3888;2181 server.3=${AWS3HOSTNAME}:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: ruok, stat, mntr
    restart: always
    command: zkServer.sh start-foreground
    #volumes:
    #  - /home/ubuntu/hadoop/zoo.cfg:/conf/zoo.cfg
networks:
  bridge:
    